### ISSUE TITLE
Package Imports

### ISSUE THREAD

**Issue by spurioushound** [RyanHornby/csSampling#1]
Hey there,

I was trying to install the package via devtools and it was running into an issue of not finding the dependent packages. Can you specify within the package build to download/update the dependencies? I installed them separately and it installed after that but I had to do some troubleshooting.

**Comment by RyanHornby** [comment]
What packages did you have to install separately?

**Comment by spurioushound** [comment]
Nevermind, I uninstalled the package to see which one was the problem but it looks like you have added in the import since I first installed it.
