### ISSUE TITLE
Package Requirements

### ISSUE THREAD

**Issue by spurioushound** [RyanHornby/csSampling#2]
I was trying to run through some of the code and some of the functions were not available through just loading the csSampling package. The one I noted was rstan not importing when I ran library(csSampling) and I had to run the library(rstan) separately.

**Comment by RyanHornby** [comment]
Which functions were you trying to run?

**Comment by spurioushound** [comment]
I was trying to run the proportions test which requires the stan_model() function. 

It was sending me an error when I was trying to run through the script when only specifying csSampling with library().

**Comment by RyanHornby** [comment]
Ok, the rstan, brms, and survey packages should now load when you run library(csSampling).
