### ISSUE TITLE
helper function fix

### ISSUE THREAD

**Issue by mrdwill** [RyanHornby/csSampling#4]
The current helper function list_2D_row_subset will drop dimensions of 1. We only want it to drop the first dimension of 1 but leave the others alone. This will be a problem if for example if we are fitting an intercept only regression model.

Here's the current code:
`function (nmlist, rindex) 
{
    temp_list <- list()
    for (k in 1:length(nmlist)) {
        ldim <- length(dim(nmlist[[k]]))
        lcommas <- paste(rep(",", ldim - 1), collapse = " ")
        eval(parse(text = paste("temp_list$", names(nmlist)[k], 
            " <- ", "(nmlist$", names(nmlist)[k], 
            ")[rindex", lcommas, "]", sep = "")))
    }
    return(temp_list)
}`
Here's the update we'll need to make and test:
`function (nmlist, rindex) 
{
    temp_list <- list()
    for (k in 1:length(nmlist)) {
	  tmpdim <- dim(nmlist[[k]])
        ldim <- length(tmpdim)
        lcommas <- paste(rep(",", ldim - 1), collapse = " ")
	 #copy over to new list - drop = FALSE retains ALL dimensions
        eval(parse(text = paste("temp_list$", names(nmlist)[k], 
            " <- ", "(nmlist$", names(nmlist)[k], 
            ")[rindex", lcommas, ",drop = FALSE]", sep = "")))
       #drop only first dimension of array - not others of size 1
	 if(ldim > 1){
	  eval(parse(text = paste("temp_list$", names(nmlist)[k], 
            " <- ", "array(temp_list$", names(nmlist)[k], ", dim = tmpdim[-1])", sep = "")))
       }	  	
    }
    return(temp_list)
}`

I hope to branch this soon to have it available. I'm a little rusty with package development and github, so thank you all for your patience.

**Comment by mrdwill** [comment]
Actually the above is still not correct. For now I'm posted a working example here:
https://discourse.mc-stan.org/t/survey-weights-in-brms-stan-simulation-based-on-design-effect-feedback-sought/28625/10?u=mrwilli

**Comment by RyanHornby** [comment]
Just to clarify, the current list_2D_row_subset should be changed to:
```
list_2D_row_subset <- function (nmlist, rindex) 
{
    temp_list <- list()
    for (k in 1:length(nmlist)) {
	  tmpdim <- dim(nmlist[[k]])
        ldim <- length(tmpdim)
        lcommas <- paste(rep(",", ldim - 1), collapse = " ")
	 #copy over to new list - drop = FALSE retains ALL dimensions
        eval(parse(text = paste("temp_list$", names(nmlist)[k], 
            " <- ", "(nmlist$", names(nmlist)[k], 
            ")[rindex", lcommas, ",drop = FALSE]", sep = "")))
       #drop only first dimension of array - not others of size 1
	 if(ldim > 1){
	  eval(parse(text = paste("temp_list$", names(nmlist)[k], 
            " <- ", "array(temp_list$", names(nmlist)[k], ", dim = tmpdim[-1])", sep = "")))
       }
      #if only had 1 dim which is the MCMC draw, make a double (no dim), rather than an array of dim 1 or 0
	if(ldim == 1){
	  eval(parse(text = paste("temp_list$", names(nmlist)[k], 
            " <- ", "as.double(temp_list$", names(nmlist)[k], ")", sep = "")))
	}	  	
    }
    return(temp_list)
}
```

Correct?

**Comment by mrdwill** [comment]
Yes, please.

**Comment by RyanHornby** [comment]
Done.
