### ISSUE TITLE
Using design objects for subpopulation estimates

### ISSUE THREAD

**Issue by TimothyRaxworthy** [RyanHornby/csSampling#6]
Hello,

I am wondering if it is possible to use the cs_sampling_brms() function will work after taking a subset of a design object. For example:

```
dhpacc <- svydesign(data = hpacc_dta_analysis, ids = ~psu_num, strata = ~stratum_num, weights = ~wpopnr_sample_statin_dm, nest = T)


#sub pop of the population correctly for unconditional analysis
dhpacc_sub <- subset(dhpacc, sample_statin_dm == 1 & 
                                survey_year == "2016")
```

When I attempt to run the model I get an error saying that the stan model weights and the survey weights don't match.

**Comment by mrdwill** [comment]
Thank you for raising this
We have an example here: https://github.com/fhmcguire/NSDUH_intersectional_depression/blob/main/02_nsduh_analysis.R
See lines 120-144. The trick is to use the calibrate function to rescale the weights to average to 1.

We should plan to add an example with this package.

**Comment by TimothyRaxworthy** [comment]
Thank you for responding with your code. This works! I was able to get the sampling to start using a different method but it was in a more eyebrow raising way so I will compare the results using both methods.
